baseURL = "http://example.org/"
languageCode = "en-us"
title = "Vytautas Kontrimas"
theme = "researcher"

math = true

[menu]
[[menu.main]]
name = "Projects"
url = "/projects"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2